global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using NutriTrack.Application.Common;
global using NutriTrack.Application.Interfaces;
global using NutriTrack.Domain.FoodCatalog;
global using NutriTrack.Domain.Identity;
global using NutriTrack.Domain.MealLogging;
global using NutriTrack.Domain.Recipes;
global using static Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions;
