global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using NutriTrack.Application.Features.Identity;
global using NutriTrack.Application.Features.MealLogging;
global using NutriTrack.Application.Features.Recipes;
global using NutriTrack.Infrastructure;
global using Microsoft.OpenApi;
